### ISSUE TITLE
[FEATURE] Write all the tests! 🙆🏼‍♂️

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#121]
As discussed on the standup we need to divide and conquer the task of writing the unit tests.

The initial setup and test examples have been merged to the `release/3.1.0` branch so you can branch from there. The GH Actions are also set up, so that will work as well 🙂 .

@infinum/wordpress-team you can comment which parts you'll like to test so that we don't overlap.

**Comment by gabriel-glo** [comment]
- [ ] Config
- [ ] ThemeOptions
- [ ] View
- [ ]  CustomTaxonomy

**Comment by dingo-d** [comment]
- [ ] Helpers
- [ ] CustomPostType
- [ ] CustomMeta
- [ ] Db

**Comment by iruzevic** [comment]
- [x] ModifyAdminAppearance
- [x] Login
- [x] CiExclude

**Comment by IvanGrginovInf** [comment]
[ ] Rest fields
[ ] Rest routes

**Comment by kmaric69** [comment]
For starters:
- [ ] Menu
- [ ] Media

**Comment by goranalkovic-infinum** [comment]
Let's try this out:

- [ ] Manifest

**Comment by volfkarlo** [comment]
I'll try this ones
- [ ] Enqueue/Blocks

**Comment by iobrado** [comment]
I'll try this
 [ ] Enqueue/Theme

**Comment by IvanGrginovInf** [comment]
- [ ] Autowiring
