### ISSUE TITLE
Add generator for privacy data handling

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-libs#126]
In order to be GDPR compliant, we could add a generator for a class / page that handles user data deletion on request.

Reference: https://github.com/dingo-d/woo-solo-api/blob/feature/2.0.0-update/src/Privacy/DataHandling.php

**Comment by IvanGrginovInf** [comment]
But we don't have any kind of mechanism for generating custom tables, no? (i.e. no `wp boilerplate custom_tables_stuff`)

So until we don't I don't see why we'd need this. If you implement some data in custom tables you should probably implement this yourself as well.

That being said, I'd keep this open for when / if we implement such functionality.

**Comment by dingo-d** [comment]
This is more plugin oriented than themes definitely. And useful when we have custom things we need to export. I'm not sure we'll ever add the create custom tables stuff, I think that would mean we'd create our own ORM of sorts, and that's a rabbit hole I'd rather not go to 😄

**Comment by IvanGrginovInf** [comment]
Makes sense, in that case how about we close this ticket and add short note (page) in documentation about this with an attitude of "Hey this is supported by core but if you have custom tables you need to implement that part yourself". (if we need to mention this at all, we don't really need to reference every part of WP in our boilerplate - same as we currently don't for things like for example custom admin tables)
