### ISSUE TITLE
Remove force update from the setup script

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#142]
The following snippet:

https://github.com/infinum/eightshift-libs/blob/92fb2da59882e9a13fa585fd1f00ed305722869d/src/Setup/Setup.php#L54-L58

Will always overwrite the core update even if we don't need it to. For instance, if I want to use this command to deploy the changes to the staging setup, I don't need it to run if the version hasn't changed. 

With `--force` argument, the WP would always reinstall on every deployment. Which is unnecessary.

**Comment by IvanGrginovInf** [comment]
@dingo-d  I think `--force` is needed if you're downgrading. In which case we'd need to add logic to detect if current change is downgrade / update and then apply `--force` if necessary.

**Comment by dingo-d** [comment]
Did we ever had the need to downgrade the WP version? I'm curious because I've never had this requirement so far. If it's a legit use case then I'd rather add an extra flag for this.

**Comment by IvanGrginovInf** [comment]
I mean, what if you update by mistake (accidentally change it in `setup.json` and deploy). I'd say there's a valid case to be made for downgrading.

**Comment by dingo-d** [comment]
I'm working on deploying the process using deployer, so I don't think that will be needed. I'll have to see how to handle it all tho.
