### ISSUE TITLE
[BUG] Bug when setuping the theme for the first time

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#144]
I went to test the bem menu on a clean theme, I used the release/3.1.0 branch and the bem menu branch on the frontend libs, and I ran into a strange issue, not sure where the problem lies tbh.

When setting up the theme using the `wp boilerplate setup_theme` command, it looks like when copying the components, the command for blocks is somehow used, and all the files and folders for blocks are created for components (transforms, hooks, etc.).

And the command failed on the footer component because the command tried to copy the footer editor component (which doesn't exist).

This happens in the new 3.1.0 release branch so I suspect there is an issue with changing the CLI commands.

**Comment by iruzevic** [comment]
fixed will work out of the box in the new release
