### ISSUE TITLE
Add scoping option

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#15]
We should probably add this everywhere in libs (or maybe just here and in boilerplate).

It's a lib to prevent namespace issues in the dependencies.

https://deliciousbrains.com/php-scoper-namespace-composer-depencies/

**Comment by IvanGrginovInf** [comment]
This should definitely be added once we get boilerplate working as a plugin (when it will be a real possibility that a user has a theme and 2-3 plugins installed created using boilerplate, all possibly using different version of https://github.com/infinum/eightshift-libs

**Comment by iruzevic** [comment]
done
