### ISSUE TITLE
[BUG] Creating taxonomy will capitalize the textdomain in the contents

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#152]
## Describe the bug
When creating a custom taxonomy using

```bash
wp boilerplate create_taxonomy
```

The textdomain in the labels will be capitalized. Not sure what happens to text domain with a dash in it.

## Steps to Reproduce
1. Setup theme
2. Try to create a custom taxonomy
3. Check the `label` field in the `getTaxonomyArguments()` method
4. The text domain should be lowercased

## Your Environment
* PHP version: 7.4.14
* Development environment: Valet
* Server type: Nginx
* Operating System and version: MacOS Bug Sur 11.2.2
* Libs version: 3.0.4

**Comment by iruzevic** [comment]
Currently textdomain is replaces with the project name space. If you agree I would leave it like this.

I have tested and the bug here was fixed

**Comment by iruzevic** [comment]
we can lower case namespace but if you have something like this 

SomethingCoolNamespace you will get somethingcoolnamespace that looks ugly

**Comment by dingo-d** [comment]
From the [official wp docs](https://developer.wordpress.org/themes/functionality/internationalization/#text-domain)

> The text domain name must use dashes and not underscores and be lowercase. For example, if the theme’s name My Theme is defined in the style.css or it is contained in a folder called my-theme the text domain should be my-theme.

**Comment by iruzevic** [comment]
ok probam vidjeti kaj mogu napraviti

**Comment by IvanGrginovInf** [comment]
> @iruzevic iruzevic linked a pull request that will close this issue on 14 Apr

This seems to work / has been fixed in a previous PR, closing issue.
