### ISSUE TITLE
Constant name name must be statically referenced

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#17]
I started to write unit tests ([branch](https://github.com/infinum/eightshift-libs/tree/feature/add-tests)), and when I created a fake plugin, I noticed that the hook name used for plugins cannot be changed because it's referenced as `self` inside the method `get_register_action_hook()`.

https://github.com/infinum/eightshift-libs/blob/1fc28c61e7134af5caf0d7730fe035af31bf6f12/src/class-main.php#L64-L66

This means that it cannot be overridden in the plugin. It needs to be set to `static` so that we can use late static binding to change it in plugins.

I've fixed this in the testing branch (because I want my tests to pass).

**Comment by iruzevic** [comment]
there are no more selfs:: any where
