### ISSUE TITLE
[BUG] - Config::getProjectPath() not working correctly when BP used as a plugin

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-libs#183]
`Config::getProjectPath()` not working correctly when BP is used as a plugin.

Steps to reproduce:
1. Get a vanilla install with twentytwentyone theme
2. Install new BP plugin
3. `wp boilerplate setup_theme` will fail because of missing global blocks `manifest.json` (because `Config::getProjectPath()` looks for it in `wp-content/themes/twentytwentyone` folder).

Error:
```
Uncaught VirtualGalleryVendor\EightshiftLibs\Exception\InvalidBlock: Global blocks settings manifest.json is missing on this location: /Users/YOUR.USER.NAME/valet-park/site-name/wp-content/themes/twentytwentyone//src/Blocks/manifest.json. in /Users/YOUR.USER.NAME/valet-park/site-name/wp-content/plugins/YOUR-PLUGIN-NAME/vendor/infinum/eightshift-libs/src/Exception/InvalidBlock.php:100 Stack trace: #0 /Users/YOUR.USER.NAME/valet-park/site-name/wp-content/plugins/YOUR-PLUGIN-NAME/vendor/infinum/eightshift-libs/src/Blocks/AbstractBlocks.php(369)
...
```

How to (temporarily fix it).
---
In your plugin's Config.php override parent (`AbstratConfigData`) `getProjectPath()` method like so:
```php
	public static function getProjectPath(string $path = ''): string {
		return \trailingslashit(dirname(dirname(__DIR__)));
	}
```

**Comment by iruzevic** [comment]
This should be fixed with the method used from the @dingo-d project.
https://github.com/infinum/eightshift-libs/blob/release/3.1.0/src/Config/AbstractConfigData.php

Can we test why is this not working?

**Comment by dingo-d** [comment]
So the fix would be to modify this

https://github.com/infinum/eightshift-libs/blob/01a6690d26499d544cdf60eaaa0024484111bdbe/src/Config/AbstractConfigData.php#L37

to be `\trailingslashit(dirname(__DIR__, 2));` ?

**Comment by IvanGrginovInf** [comment]
Nope because `\trailingslashit(\get_template_directory()) . $path,` (1 line above this) will detect the active theme regardless of what it is and use that. Maybe if we invert the order to first check in the folder.

**Comment by IvanGrginovInf** [comment]
Having it as this might work:

```php
		$locations = [
			\trailingslashit(__DIR__) . $path,
			\trailingslashit(\get_stylesheet_directory()) . $path,
			\trailingslashit(\get_template_directory()) . $path,
		];
```

**Comment by dingo-d** [comment]
I had, on one client plugin this

```php
protected function getLocations(string $uri): array
    {
        return [
            trailingslashit(\get_stylesheet_directory()) . $uri,
            trailingslashit(\get_template_directory()) . $uri,
            trailingslashit(dirname(__DIR__, 2)) . $uri,
        ];
    }
```

And that always worked for me 🤷🏼‍♂️ 

The consuming code was

```php
protected function validate(string $uri): string
    {
        $uri = $this->checkExtension($uri, static::VIEW_EXTENSION);

        foreach ($this->getLocations($uri) as $location) {
            if (is_readable($location)) {
                return $location;
            }
        }

        if (!is_readable($uri)) {
            throw InvalidUri::fromUri($uri);
        }

        return $uri;
    }
```
