### ISSUE TITLE
Replace hardcoded templates with code generation

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#214]
## Is your feature request related to a problem? Please describe.
First of all, this is a **proposal** and one that we can or don't have to implement in the future. So don't bite my head off 😂 

Reading on the internet (as one does) I came upon this nifty little package: https://github.com/laminas/laminas-code/

At first, I was like: huh? 🤔 What on earth would I need that for?!

But then it dawned upon me: we could actually use this to get rid of the example 'templates' in our code.

The templates are fine, and all the methods we have to replace certain parts of the code work and are a nice part of one big fluent interface, and all that is super cool. But what if we didn't have to have them?
What if we could offload this replacement, generation, copy/pasting part to another part of the code that is tested and works?

What are the benefits of such an approach?

Mostly less of our code. We could remove most (if not all) methods in the AbstractCli class, and use the generator code to generate files. Just pass the parameters from the CLI into the generation code and that's it.

The syntax seems complex, but not insurmountable.

## Oh, great, another rewrite 🙄 

This is a proposal. If we see that there are no benefits to it, we don't need to do it.

There are a couple of things that we should take into account while discussing this:

1. What are all the benefits of doing this? _(besides learning to work with the new package)_
2. Are there going to be any performance benefits to this? _(profiling needed)_
3. Is this going to be a breaking change? _(it shouldn't be)_
4. ...

**Comment by iruzevic** [comment]
I will close this as it would take a major refactor and it will not gain use much, tnx for the suggestion
