### ISSUE TITLE
Deprecated functions in WP 5.8

### ISSUE THREAD

**Issue by simun-ivanac** [infinum/eightshift-libs#233]
## Describe the bug
Functions that are no longer valid in WP 5.8 and can cause compatibility issues.

## Your Environment
* PHP version: 7.4
* Libs version: 4.0

## Additional context

PHP Deprecated:  `block_categories` is <strong>deprecated</strong> since version 5.8.0! Use `block_categories_all` instead. in .../functions.php on line 5458

PHP Deprecated:  `allowed_block_types` is <strong>deprecated</strong> since version 5.8.0! Use `allowed_block_types_all` instead. in .../functions.php on line 5458

PHP Deprecated:  `block_categories` is <strong>deprecated</strong> since version 5.8.0! Use `block_categories_all` instead. in .../functions.php on line 5458

PHP Deprecated:  `block_editor_settings` is <strong>deprecated</strong> since version 5.8.0! Use `block_editor_settings_all` instead. in .../functions.php on line 5458

**Comment by dingo-d** [comment]
These were supposed to be fixed in https://github.com/infinum/eightshift-libs/pull/223.

There should be

```php
// Only allow custom-built blocks.
if (\is_wp_version_compatible('5.8')) {
	\add_filter('allowed_block_types_all', [$this, 'allowOnlyCustomBlocks'], 21, 2);
} else {
	\add_filter('allowed_block_types', [$this, 'allowOnlyCustomBlocksOld'], 21, 2); // @phpstan-ignore-line
}
```

and 

```php
// Create new custom category for custom blocks.
if (\is_wp_version_compatible('5.8')) {
	\add_filter('block_categories_all', [$this, 'getCustomCategory'], 10, 2);
} else {
	\add_filter('block_categories', [$this, 'getCustomCategoryOld'], 10, 2);
}
```

hooks in your `Blocks.php` file.

**Comment by iruzevic** [comment]
this is fixed
