### ISSUE TITLE
Auto documentation generator

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-libs#242]
Research auto docs generator like phpDoc2, phpDoc3, phpDox, etc

**Comment by mbmjertan** [comment]
Going through available tools for this, here are some thoughts.

* phpDocumentor is pretty good, and very customizable
* phpDox is not really actively maintained, and not customizable at all (and very ugly!)
* Doxygen is not PHP-specific, so it produces a bit of noise along the way, but it's amazingly configurable, a bit faster than phpDocumentor and handles inheritance and overriding functions much better (i.e. for any method that's reimplemented, you're alerted about that, and for every class/interface/... you get an inheritance diagram)
* I've also taken a look at many, many other solutions, but these two are the only ones that stand out as any good

It is a bit more difficult to configure Doxygen than phpDocumentor. While phpDocumentor uses Twig, Doxygen uses... Doxygen 😄 Doesn't seem too difficult, as it's at least documented unlike phpDocumentor (which has very poor documentation on templating, although it has a few examples in the repo)
See [https://www.doxygen.nl/manual/customize.html](https://www.doxygen.nl/manual/customize.html).

I've attached documentation generated for eightshift-libs and eightshift-boilerplate by phpDocumentor and Doxygen so you can see what gets generated for yourself: [phpDocumentor.zip](https://github.com/infinum/eightshift-libs/files/8315759/phpDocumentor.zip)
[Doxygen.zip](https://github.com/infinum/eightshift-libs/files/8315791/Doxygen.zip)


## Example class documentation for `AbstractAdminMenu`

**Doxygen**
![Screenshot 2022-03-21 at 14 27 10](https://user-images.githubusercontent.com/1742806/159270663-5614f749-b428-4cc5-8105-9e0b2f4321e0.png)

**phpDocumentor**
![Screenshot 2022-03-21 at 14 27 33](https://user-images.githubusercontent.com/1742806/159270820-a8e215b9-aab1-410b-9884-1dfd57baadc1.png)

## Example method documentation for `AbstractAdminMenu\processAttributes, processAdminMenu`

**Doxygen**
![Screenshot 2022-03-21 at 14 30 48](https://user-images.githubusercontent.com/1742806/159271426-eb1654bf-8cb4-43c1-a4e2-2ffa66638af8.png)


**phpDocumentor**
![Screenshot 2022-03-21 at 14 27 23](https://user-images.githubusercontent.com/1742806/159271093-49d7d51b-8864-48a0-afec-f0e1ec511aa2.png)

![Screenshot 2022-03-21 at 14 30 59](https://user-images.githubusercontent.com/1742806/159271517-5b613e6c-ac5a-4636-862f-2606dbbdaa6e.png)
