### ISSUE TITLE
Optimise loading of inline style tags for css variables

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-libs#246]
# Develop:
1. Current mode stays the same and should be used only in develop mode

# Production, staging:
1. Output variables to a global variable
2. Store breakpoints in the correct place in the global variable
3. Output one style tag enqueue part of the loading scripts so it is always loaded before all style tags
4. Minimize output

**Comment by mbmjertan** [comment]
Wholeheartedly support this, as this has an impact on our a11y compliance (https://github.com/infinum/eightshift-frontend-libs/issues/491).
