### ISSUE TITLE
Issues with `setup_theme` command on Windows OS

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-libs#261]
### Describe your bug

When running `wp boilerplate setup_theme` on Windows we get the following error message:

```
Warning: mkdir(): No such file or directory in E:\valet\boil\wp-content\themes\test\vendor\infinum\eightshift-libs\src\Cli\AbstractCli.php on line 295
Warning: fopen(/E:\valet\boil\wp-content\themes\test/src\Config/Config.php): failed to open stream: No such file or directory in E:\valet\boil\wp-content\themes\test\vendor\infinum\eightshift-libs\src\Cli\AbstractCli.php on line 300
Error: File /E:\valet\boil\wp-content\themes\test/src\Config/Config.php couldn\'t be created. There was an error.
```

The issue seems to be due to the differences in path in Windows and UNIX based systems. 
I got some good results by replacing each instance of `/` characters with `DIRECTORY_SEPARATOR` global variable in `AbstractCli.php` and `BlocksCli.php`.

Also there seems to be an issue when creating all other folders that are in Blocks namespace:
```
		foreach ($folders as $folder) {
			if (!file_exists($folder)) {
				system("mkdir -p {$folder}");
			}
		}
```

I think this is an issue that Command Prompt is being used by default in this case and it doesn't support `mkdir` command. I'll test out if this will be fixed when changing  to Powershell.

### Steps to Reproduce

1. Install WP in Windows development environment (WAMP, Valet for Windows, .etc)
2. run `npx create-wp-project` from `/themes/` folder and go through initial steps
3. Activate new theme.
4. Run `wp boilerplate setup_theme`

### Expected behavior

It's expected that installation goes through all steps outlined in `CliInitTheme.php` and we get a working Boilerplate theme.

### Environment info

- PHP 7.4
- Valet for Windows, but this is present on all environments that are running the commands inside Windows OS
- Node 16.14
- Nginx
- Windows 10
- ES Libs 4.0

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by dingo-d** [comment]
We should probably have to replace all the system calls with the PHP equivalent. 

For instance [mkdir](https://www.php.net/manual/en/function.mkdir.php), or [cp](https://www.php.net/manual/en/function.copy.php), etc.

**Comment by iruzevic** [comment]
this is fixed
