### ISSUE TITLE
`setup_theme` fails on macOS

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-libs#267]
### Describe your bug

Running `setup_theme` on macOS on a clean project (created using `npx create-wp-project --eightshiftBoilerplateBranch='develop' --eightshiftLibsBranch='develop' --eightshiftFrontendLibsBranch='develop'`) results in this:

```
mariobornamjertan@Infinums-MacBook-Pro ~/d/w/w/t/testing-theme> wp boilerplate setup_theme
Success: File /Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Config/Config.php successfully created.
Success: File /Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Main/Main.php successfully created.
Success: File /Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Manifest/Manifest.php successfully created.
Success: File /Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Enqueue/Admin/EnqueueAdmin.php successfully created.
Success: File /Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Enqueue/Blocks/EnqueueBlocks.php successfully created.
Success: File /Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Enqueue/Theme/EnqueueTheme.php successfully created.
Success: File /Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Menu/Menu.php successfully created.
Error: The wrapper exists in your project on this "/Users/mariobornamjertan/dev/wpt/wp-content/themes/testing-theme/src/Blocks/wrapper" path. Please check or remove that folder before running this command again.
```

This happens whether or not you run`composer update`.
Funny enough, the `src` folder itself doesn't exist before `setup_theme` is run:

```
> ls
404.php             README.md           footer.php          node_modules/       phpcs.xml.dist      single.php
CHANGELOG.md        babel.config.js     functions.php       package-lock.json   phpstan.neon.dist   style.css
CODE_OF_CONDUCT.md  composer.json       header.php          package.json        postcss.config.js   vendor/
LICENSE             composer.lock       index.php           page.php            screenshot.png      webpack.config.js
```

### Steps to Reproduce

1. `npx create-wp-project --eightshiftBoilerplateBranch='develop' --eightshiftLibsBranch='develop' --eightshiftFrontendLibsBranch='develop'`
2. `cd {theme_name_here}`
3. `wp boilerplate setup_theme`

### Expected behavior

A correctly setup theme.

### Environment info

macOS 12.3, running Valet.

```
> php -v
PHP 7.4.28 (cli) (built: Mar  1 2022 09:40:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.28, Copyright (c), by Zend Technologies

```

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by mbmjertan** [comment]
I've looked into this, and seems like the root cause is in commit https://github.com/infinum/eightshift-libs/commit/2fcc29d300cf4f3f169ede451c24a22e8d7e2f55, as the whole Blocks folder gets copied over before `use_wrapper`, `use_component` and `use_block` calls.

To confirm that this is the case, I've added a `$overwrite = true` parameter to the `copyRecursively` method in `AbstractCli` and changed the copy logic to as follows:

```php
if (!\file_exists($destinationPath) || $overwrite) {
  \copy($item->getPathname(), $destinationPath);
}
```

After changing the `blocksInit` logic to this, everything works as expected:


```php
		$this->copyRecursively("{$rootNode}/assets/", "{$folders['assetsGlobal']}/");
		$this->copyRecursively("{$rootNode}/src/Blocks/assets/", "{$folders['assets']}/");
		$this->copyRecursively("{$rootNode}/src/Blocks/variations/", "{$folders['variations']}/");

		WP_CLI::runcommand("{$this->commandParentName} use_wrapper {$this->prepareArgsManual($args)}");

		foreach (static::COMPONENTS as $component) {
			WP_CLI::runcommand("{$this->commandParentName} use_component --name='{$component}' {$this->prepareArgsManual($args)}");
		}

		foreach (static::BLOCKS as $block) {
			WP_CLI::runcommand("{$this->commandParentName} use_block --name='{$block}' {$this->prepareArgsManual($args)}");
		}

		$this->copyRecursively("{$rootNode}/src/Blocks/", "{$folders['blocks']}/", false);

		WP_CLI::success('Blocks successfully set.');
```

However, I wouldn't go with this fix in Libs as it's wasteful and because I don't understand why commit https://github.com/infinum/eightshift-libs/commit/2fcc29d300cf4f3f169ede451c24a22e8d7e2f55 changed copying the global block manifest to copying the whole `Blocks` folder recursively.

**Comment by dingo-d** [comment]
@iruzevic ☝🏼 😄

**Comment by iruzevic** [comment]
this is fixed
