### ISSUE TITLE
Custom taxonomy doesn't have the label generator in it

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#274]
### Describe your bug

CPTs have embedded label generator, custom taxonomies should have as well

### Steps to Reproduce

1. Create a custom taxonomy or update libs on an existing project which uses the label generator
2. See the errors

### Expected behavior

We need to add, maybe a trait for the reusability between CPTs and CTs, for the method at least. The constants need to be defined in the abstract classess. 

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
Implemented in the current release
