### ISSUE TITLE
Fix all the argument names in public/static methods

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#281]
### Describe your feature request

We should go through all the public methods and static helpers we are using and make sure that the argument names don't use reserved PHP keywords because that would throw an error in PHP8.

Similar to what WP is doing in this ticket: https://core.trac.wordpress.org/ticket/55327

The things to watch out for would be 

```php
function foo(string $string, array $list) {}
```

which should be changed to something like this:

```php
function foo(string $textString, array $listOfThings) {}
```

so that it can be used like

```php
foo(listOfThings: [1, 2, 3], textString: 'hi!');
```

### Describe the solution you'd like

1. Go through the code
2. Fetch all the public-facing methods/helpers
3. Check if they use reserved [PHP keyword](https://www.php.net/manual/en/reserved.keywords.php)
4. Make a replacement

### Environment info

- PHP Version: 8+

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by mbmjertan** [comment]
I've went through our eightshift-libs, and we have a few instances where we use reserved words as argument names in public methods. I'd like to fix the issue in private and protected methods as well, so we're able to use named arguments internally as well.

Have in might that there are _a lot_ of violations of this in our Composer dependencies though.

**Comment by dingo-d** [comment]
> Have in mind that there are a lot of violations of this in our Composer dependencies though.

We can only open issues/PR in these packages if we encounter it 🙂
