### ISSUE TITLE
Unify the CLI command descriptions

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#284]
### Describe your feature request

The command short descriptions are kinda all over the place. We should unify them more.

### Describe the solution you'd like

Pick one and stick to it.

We have `Generates ... class file`, and also `Generates SomeClass class`. We should pick one (or create an even better description 🤷🏼‍♂️) and use that.

### Screenshots, screen recording, code snippet

<img width="1190" alt="Screenshot 2022-04-27 at 16 18 59" src="https://user-images.githubusercontent.com/8638515/165540872-cd893a8d-a378-43ce-86e5-62b4ae7fc8d2.png">

### Environment info

Not important in this case.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
done
