### ISSUE TITLE
checkAttr should throw a more informative exception when a component doesn't provide a default

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-libs#290]
Assume you have a `card` block or component, which uses a `button` as it's dependency, e.g. 

```
"components": {
    "button": "button"
}
```

Assume the `button` component manifest contains this:
```
"attributes": {
   "buttonUrl": {
        "type": "string"
   }
}
```

In that case, rending a `card` component without the `cardButtonUrl` attribute explicitly set can result in an exception being thrown when calling `Components::checkAttr('cardButtonUrl', $attributes, $manifest)`, as there isn't a default value set.

However, this exception will be `InvalidManifest::missingManifestItemException`, which is misleading is these circumstances:

https://github.com/infinum/eightshift-libs/blob/585e4dc07a0f2a8c81c502da915a901752302831/src/Exception/InvalidManifest.php#L27

**Comment by iruzevic** [comment]
fixed in the latest releae
