### ISSUE TITLE
Update GH Action workflows

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#305]
### Describe your feature request

Current workflows are not up to date.

Actions checkout has a version 3

[ramsey/composer-install](https://github.com/ramsey/composer-install) is on version 2.

### Describe the solution you'd like

Update the version in the workflow yaml files

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
this is implemented
