### ISSUE TITLE
Explore uses in tests

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-libs#309]
### Describe your feature request

Try to see if you can use uses to bind this to just this test case.

https://pestphp.com/docs/underlying-test-case#uses

### Describe the solution you'd like

for better optimisations for tests

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by dingo-d** [comment]
Branch where I've done the above: https://github.com/infinum/eightshift-libs/tree/optimize-tests
