### ISSUE TITLE
PHP 8+ support

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#315]
### Describe your feature request

We should start checking for PHP 8+ compatibility/issues in the libs.

### Describe the solution you'd like

1. Add GH Actions matrix checks, with allowed failures for PHP 8+ (since we are still not supporting them, it's ok that they fail)
2. Modify the phpcs config so that the supported version is upped to PHP8
3. Check if there are any forbidden keywords used as method arguments
4. Consolidate and agree on method argument naming (after PHP 8, any change in argument name will be a BC break!)
5. Update code to be written using PHP8 syntax with a fallback for PHP 7.4 version where possible
6. Test everything

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
We have started working on this support all fixes are located in this `develop-php8` branch

**Comment by iruzevic** [comment]
this is done in the latest release
