### ISSUE TITLE
Consider using realpath instead of manually constructing paths

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-libs#318]
### Describe your feature request

The [`realpath`](https://www.php.net/manual/en/function.realpath.php) function seems to provide similar functionality to what we're doing (mostly) manually or with helpers constructing the paths by concatenating their parts with `DIRECTORY_SEPARATOR`. It also resolves paths into absolute paths, and is cached.

### Describe the solution you'd like

Consider using `realpath` instead of the current approach.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
tried it and it is not working as expected and there are so many changes to be made that I will not make this as this works ok

**Comment by iruzevic** [comment]
tnx for the suggestion
