### ISSUE TITLE
Default naming when running init theme CLI command is wrong

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#338]
### Describe your bug

I noticed that in the config the default name is left as `Boilerplate` instead of being changed to project name, or the dash separated project name (which is better because this is used as a name in the rest route).

### Steps to Reproduce

Setup project from scratch
Start the init theme
Check the config class for the naming

### Expected behavior

Name shouldn't be default.

### Environment info

- PHP 7.4
- MacOs Monterey 12.6
- Nginx
- Latest libs

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
this is fixed
