### ISSUE TITLE
LoadMore route is copied into projects in a PSR-4 noncompliant way

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-libs#340]
### Describe your bug

When you use `npx create-wp-project` with the Eightshift Libs branch set to `develop`, the `LoadMoreRoute` example class is copied over to `src/Rest/Routes/LoadMoreRoute.php` (while it's in Libs as `src/Rest/Routes/LoadMore/LoadMoreRouteExample.php`), resulting in it having the namespace `ProjectName\Rest\Routes\LoadMore`, but without accounting for that in the path. 

This results in a PSR-4 noncompliance exception, and might be related to 89ea1b7a47fdcccbf66ba447b185950d2ff97f28.

### Steps to Reproduce

1. Create a project from the develop branch
2. Use `wp boilerplate init all` or otherwise pull the class into your project using `wp boilerplate`
3. Your site should be broken with a PSR-4 noncompliance exception

### Expected behavior

Site shouldn't be broken with a PSR-4 noncompliance exception 😄 

### Environment info

PHP 7.4.30, Libs on `develop`

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by dingo-d** [comment]
Can you make a PR with a fix? This shouldn't be a difficult fix to make 🙂

**Comment by iruzevic** [comment]
quick for now I will revert back to review this in the future release

**Comment by dingo-d** [comment]
> quick for now I will revert back to review this in the future release

What is quick? XD

Not sure why the issue is closed if it's not fixed 😬

**Comment by iruzevic** [comment]
I made a quick hack, wrote a reply here, than felt guilty and fixed it the right way. So this is fixed the right way 😉
