### ISSUE TITLE
CLI command to update project version

### ISSUE THREAD

**Issue by piqusy** [infinum/eightshift-libs#343]
### Describe your feature request

Create a CLI command to update project version in increments so we can bump versions in between releases.
Do this for the following files in theme:

- functions.php
- package.json
- styles.css
- src/Config/config.php

### Describe the solution you'd like

Bump version in increments with option for increasing minor, major or patch versions.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
this is added in the new release
