### ISSUE TITLE
Examples in the wp boilerplate create --help command are wrong

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#345]
### Describe your bug

The examples at the end are not correct (don't match the updated commands)

### Steps to Reproduce

Run the command and see the output

### Expected behavior

Correct examples should be shown when the help command is used

### Screenshots, screen recording, code snippet

<img width="989" alt="image" src="https://user-images.githubusercontent.com/8638515/196722178-7fd77e6c-d50b-43ea-87c6-aaea0d8c17fb.png">

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
tnx fixed in the latest release
