### ISSUE TITLE
Copy block/component with or without storybook parts

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#348]
### Describe your feature request

Most of the times storybook isn't really used. So we shouldn't include `docs` folder with the blocks/components by default, but only when we need them, using a `--use-storybook` flag (or `--include-storybook`).

### Describe the solution you'd like

Have a flag to include the storybook parts. This way we are reducing the clutter that te docs are making.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
we are removing storybook all together so i will close this because it is removed
