### ISSUE TITLE
Text domain slug escaped when using admin menu creation command

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#352]
### Describe your bug

Never had this happen before, so I'm not sure what changed

<img width="460" alt="image" src="https://user-images.githubusercontent.com/8638515/211015615-53032ffc-e78e-4689-b07b-ef4d8726694f.png">

The dash seems to be escaped 👀 

### Steps to Reproduce

1. Have a plugin with name that has a dash in it (`eightshift-sso` for instance 😅)
2. Create admin menu
3. Inspect the text domain

### Expected behavior

There shouldn't be a `\` in front of the dash.

### Environment info

- PHP Version: 7.4
- WSL 2
- Nginx server
- Windows 11
- Latest libs

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
this was due to imposter We will remove this so I will close it, tnx for the comment
