### ISSUE TITLE
Update PHP-DI lib

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#353]
### Describe your feature request

The PHP-DI v7 [has been released](https://php-di.org/doc/migration/7.0.html), and we should update our implementation.

### Describe the solution you'd like

Update the lib, and check the migration guide to fix what needs to be fixed.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
added in the new release
