### ISSUE TITLE
Memoize calls to manifest

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#354]
### Describe your feature request

I noticed that most of the components are doing `Components::getManifest` calls in one way or another.

And I thought to myself: could this be optimized?

The answer is obviously yes. In more ways than one.

### Describe the solution you'd like

There are several ways we can optimize these calls:

1. Use WP object cache - [wp_cache_set()](https://developer.wordpress.org/reference/functions/wp_cache_set) can utilize either memory or other object cache solutions like Redis (if used on a project). Which could save a lot of extra calls.
2. Memoization - we could memoize the calls. Memoization is a request optimization, so it's short-lived (during the request), but could still help with avoiding doing unnecessary calls all the time when going through a component tree.

Both of these two approaches could optimize things when using libs.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
I have tried and I havent produced any significant results with wp cache. I didn't use Memoization because I have read that it should be avoided if the file size is large. I will close this for now

**Comment by dingo-d** [comment]
> I have tried and I haven't produced any significant improvements with wp cache. I didn't use Memoization because I have read that it should be avoided if the file size is large. I will close this for now

None of the files in the boilerplate are that large in size to be excluded by the memoization calls. The worry you probably read was when handling things like file uploads, or something similar, where the memory impact could be greater.

I'll try to see if improvements can be made. Would make a cool thing benchmark and play around 🙂
