### ISSUE TITLE
Using wp boilerplate create post-type can produce a syntax error

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-libs#356]
### Describe your bug

This gets generated as part of the generated `getPostTypeArguments` method in the post type class, producing a fatal error:

![Screenshot 2023-02-14 at 17 09 44](https://user-images.githubusercontent.com/1742806/218793531-e3fb636a-9d00-4b26-ae89-47704148a0f8.png)

### Steps to Reproduce

`wp boilerplate create post-type --label='Blah' --plural_label='Blahs' --slug='blah' --rewrite_url='blah' --rest_endpoint_slug='blah' --capability='post' --menu_position='20' --menu_icon='dashicons-admin-settings'`

### Expected behavior

One comma instead of two.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

No

**Comment by iruzevic** [comment]
I was unable to replicate this issue
