### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#357]
### Describe your bug

Tests are failing

### Steps to Reproduce

https://github.com/infinum/eightshift-libs/actions/runs/4174064328/jobs/7227170967

### Expected behavior

Tests should be green before merge

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
done in the latest branch
