### ISSUE TITLE
Admin enqueue scripts action is missing hook suffix parameter

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#358]
### Describe your bug

As per docs: https://developer.wordpress.org/reference/hooks/admin_enqueue_scripts/

`admin_enqueue_scripts` has a parameter called `$hook_suffix`, which is used to determine on which pages the admin script should be loaded or not.

Currently, this parameter is missing, so we cannot re-add it when modifying the `enqueueStyles` or `enqueueScripts` methods, as that will throw the error

> Warning: Declaration of Project\Enqueue\Admin\EnqueueAdmin::enqueueStyles(string $hookSuffix): void should be compatible with Vendor\EightshiftLibs\Enqueue\Admin\AbstractEnqueueAdmin::enqueueStyles(): void 

We need to add this, and other parameters to all the methods that expect them, as per the public API.

### Steps to Reproduce

1. Install the project
2. Try to override the `enqueueScripts` method like
    ```php
        public function enqueueStyles(string $hookSuffix): void
        {
            parent::enqueueStyles();
            // rest of the code...
        }
    ```
3. See the above error

### Expected behavior

We should be able to correctly implement the hook callbacks.

Either specify the exact parameters - without type hints ideally as adding those, without them being explicitly checked in the core (which currently they are not), could cause confusion when some error happens, and the lib could be blamed. 
Or as a variadic parameter (as filter callbacks are variadic by nature).

A more detailed explanation of the type issue with filters can be found [here](https://core.trac.wordpress.org/ticket/51525).

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
added
