### ISSUE TITLE
Add filter to exclude some image formats from WebP conversion

### ISSUE THREAD

**Issue by goranalkovic-infinum** [infinum/eightshift-libs#362]
### Describe your feature request

If you upload a GIF for example, it'll automatically get converted to WebP, which will break the animation.

### Describe the solution you'd like

A filter could be added to list file formats that should skip WebP conversion.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by mbmjertan** [comment]
webp supports animations though? see https://developers.google.com/speed/webp/ and https://developers.google.com/speed/webp/docs/gif2webp, there should be no need for this

**Comment by goranalkovic-infinum** [comment]
@mbmjertan you're right!

However, it looks like GD doesn't support animated WebPs, and that's the one used in `imagecreatefromgif` we're using to convert.

Switching to Imagemagick should work, though.
