### ISSUE TITLE
Fix project path for pre-commit

### ISSUE THREAD

**Issue by kmaric69** [infinum/eightshift-libs#37]
## Current Behavior

When staging php files and running `npm run lint` it stops on Checking PHP Lint while giving the wrong path to the staged file.

## Possible Solution

Change line 8 in bin/lintPhp.sh from `PROJECT=`php -r "echo dirname(dirname(realpath('$0')));"`` to `PROJECT=`php -r "echo dirname(dirname(dirname(dirname(dirname(realpath('$0'))))));"``

**Comment by iruzevic** [comment]
This is old and not relative any more
