### ISSUE TITLE
[FEATURE] - Rename Enqueue Theme to Enqueue Front

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#374]
Hi!

It would be better maybe to rename the `EnqueueTheme` class to `EnqueueFront` or `EnqueueFrontend` so that, when used in plugin context, it makes more sense.

**Comment by iruzevic** [comment]
Thx for the suggestion but this would cause a major breaking change, so we will not be making this change

**Comment by dingo-d** [comment]
> Thx for the suggestion but this would cause a major breaking change, so we will not be making this change

Well if you release it in v7 it would be ok since it's a major version 👀 (major versions include breaking changes)
