### ISSUE TITLE
Replace hardcoded project version with theme version

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#379]
On the following line in the config

https://github.com/infinum/eightshift-libs/blob/d7150e882ac2c3411b80ff422c0db2766280a230/src/Config/ConfigExample.php#L40

The project version is hardcoded value. So each time you'd need to increase project version you'd have to do it manually, especially because you'd need to do it in multiple places.

It would be better to replace this with

```php
wp_get_theme()->get('Version');
```

As that will just read the version from the `style.css` of the theme, so in that case there is only one place where you'd need to track the version number (you'd probably still have to manually change the `package.json`, but that's outside of the PHP/WP scope).

**Comment by iruzevic** [comment]
agreed I did the same thing on forms
https://github.com/infinum/eightshift-forms/blob/5cf5812c00ac524650c097b8bf998146d31b27dd/src/Config/Config.php#L58

**Comment by iruzevic** [comment]
done
