### ISSUE TITLE
[IMPROVEMENT] - wp_register_script changes in version 6.3

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#390]
In WP 6.3, the core changed the `$in_footer` parameter to be an `$args` parameter array (because why not).

This will require changes wherever this function is used in the libs such as here on line 126:

https://github.com/infinum/eightshift-libs/blob/a5f24a4a5450089fc0ccb2bd06661d6ca59639f8/src/Enqueue/Admin/AbstractEnqueueAdmin.php#L121-L127

The `$args` argument can be a boolean or a false (which means currently this won't break anything on the existing projects, which is great, no matter how this 'type' is just... sigh... WordPress...) that has `strategy` and `in_footer` keys.

See more: https://developer.wordpress.org/reference/functions/wp_register_script/#parameters

**Comment by iruzevic** [comment]
this is done in the latest release
