### ISSUE TITLE
[BUG] - Redeploy doesn't change theme version and resets cache

### ISSUE THREAD

**Issue by dadadavorin** [infinum/eightshift-libs#430]
When running the same deploy process again, the theme version in `style.css` stays the same, which in turn does not reset cache and causes some functionalities to break.

In my example, `applicationBlocksEditor` files were not loading correctly due to cache not being reset after running deploy.

I can see that `setup-version-theme` [action](https://github.com/infinum/eightshift-deploy-actions-public/blob/main/.github/actions/setup-version-theme/action.yml) gets the key from `VERSION=${{ github.sha }}`, and `github.sha` refers to the last commit - and if we're running same commit again this key is the same.

This seems to be the issue, since manually changing the theme version in `style.css` also solves the caching issue.

**Comment by iruzevic** [comment]
This should be fixed
