### ISSUE TITLE
Add parameters to enqueue callback methods

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#48]
None of the enqueue methods in hooks have attributes in them. Which means that we cannot use the `$hook_suffix` parameter to check where the script should or shouldn't load.

For instance, I may want to load the admin script only on a certain post, or admin screen, and then I'd use the hook suffix to identify the page and load the script.

You may say: but we are using dynamic imports so that's not important, but what when you need to localize a script and provide it only in one place - like on a specific screen?

We should add them.

Personally, I blame WP core for not using interfaces so that we were notified that we should implement those in the first place 😄

**Comment by iruzevic** [comment]
Added, on every enqueue script you now have is<>Used method that is by default true.
