### ISSUE TITLE
Improve post type columns slug method docs

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#52]
This documentation should be improved. The method name is also a bit misleading and not self-documenting.

https://github.com/infinum/eightshift-libs/blob/42929f77d126fbd33bf778c9c44834523153e60d/src/columns/class-base-post-type-columns.php#L62-L69

The method name suggest that the return value will just be a string, but it is an array of one or many post types.

So it would be good to change the documentation since the method name change would most probably cause a backwards compatibility break.

```php
  /**
   * Return an array of post type slugs for which the new column should be added to
   *
   * @return array Array containing the post type slugs.
   *
   * @since 2.0.5
   */
  abstract protected function get_post_type_slug() : array;
```

Ideally, the method should be named like: `get_post_type_slugs`.

The same goes for other abstract classes.

**Comment by iruzevic** [comment]
Hmm from the documentation post type can't be array but  only it can be string so the naming is ok but typing is wrong. this should be changed

https://developer.wordpress.org/reference/functions/register_post_type/

**Comment by dingo-d** [comment]
The issue is that you are using this method to provide multiple different slugs to create columns in the post type screen. So it expects it to be an array (type is correct).

I don't have anything against that, it's just that the method name is misleading:

`get_post_type_slug` - return a post type slug, which is a string

vs.

`get_post_types` - return many different post types - a list (array).

**Comment by iruzevic** [comment]
yea makes sense

**Comment by iruzevic** [comment]
Can you please tackle this? Just make a change and write a detailed change log
