### ISSUE TITLE
The lock file should not be in a lib's repo

### ISSUE THREAD

**Issue by szepeviktor** [infinum/eightshift-libs#64]
if you disagree please add

`composer validate --strict` to CI

**Comment by dingo-d** [comment]
As in `composer.lock`? How come? Committing a lock file ensures that anybody who uses the lib has the same dependency versions installed.

**Comment by szepeviktor** [comment]
Noooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo :)

Composer does not take the lock file into account.
It is used only when `eightshift-libs` is not a dependency but a project.

**Comment by szepeviktor** [comment]
Look for 10 popular PHP libs and check whether they have a lock file!

**Comment by dingo-d** [comment]
Indeed it looks like it: https://getcomposer.org/doc/02-libraries.md#lock-file

**Comment by iruzevic** [comment]
done

**Comment by szepeviktor** [comment]
Thank you.
