### ISSUE TITLE
Register Custom Post Type Labels

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-libs#7]
Rethink registering custom post type labels:

> This labler function / process could be simplified. I.E. you define the labels in a function and the parent's (Base_Post_Type) function does all the work.

final class Faq extends Base_Post_Type {

  ...

  function get_labels() {
    return [
      'singular-uc' => esc_html_x( 'FAQ', 'post type upper case singular name', 'eightshift-libs' ),
      'singular-lc' => esc_html_x( 'faq', 'post type lower case singular name', 'eightshift-libs' ),
      'plural-uc' => esc_html_x( 'FAQs', 'post type upper case plural name', 'eightshift-libs' ),
      'plural-lc' => esc_html_x( 'faqs', 'post type lower case plural name', 'eightshift-libs' )
    ];
  }

  ...

}
  @IvanGrginovInf
IvanGrginovInf 18 minutes ago
Edit: First I thought about putting it in a const but then you can't have translation. This example above doesn't really simplify it all that much. Still the 'labels' => ( new Label_Generator() )->get_generated_labels( $nouns ), line is bothering me a bit.

**Comment by dingo-d** [comment]
Labels are also missing some fields that we'd need to add

https://developer.wordpress.org/reference/functions/get_post_type_labels/

Few new labels were added, notably:

5.8.0 - Added the `item_link` and `item_link_description` labels.
5.7.0 - Added the `filter_by_date` label.
