### ISSUE TITLE
Make Component::render method automatically echoed

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-libs#71]
now we need to echo the method for it to work, we should add ability to have this out of the box to mimic the $this->render_block_view() method

**Comment by dingo-d** [comment]
But the `Components::render` wraps the component in additional markup, while `render_block_view()` method just includes the PHP file.

What's wrong with echoing it out?

**Comment by iruzevic** [comment]
they both do the same thing but `render_block_view ` is used inside the blocks only and it doesn't need echo to output the template. This method is only available in blocks and not in the components.

In the components folder and everywhere else we use `Components::render` helper this method is built so it needs echo to be able to output the template. My idea is to have both methods behave the same way. 

Just and idea, I'm open to new ideas

**Comment by iruzevic** [comment]
We will not implement this.
