### ISSUE TITLE
[FEATURE] Allow assigning multiple post types on taxonomy registration

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-libs#78]
When registering a custom taxonomy by extending `Base_Taxonomy` class and implementing method `get_post_type_slug`, only thing that is possible is to return a string of post type slug. That value is passed as an argument to `register_taxonomy` by putting it in array. Because of that there is no way to assign taxonomy to multiple post types.
If we change the return type of `get_post_type_slug` method to array, this would be possible.

This was already implemented for `Base_Post_Type_Columns` class.

**Comment by iruzevic** [comment]
This is implemented in release 3..0.0
