### ISSUE TITLE
[BUG] Service example command doesn't change service name

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#88]
When I typed `wp boilerplate create_service_example --folder=post --file_name=Excerpt` the name of the class and all the comments were still `ServiceExample`.

Besides that, since we are using PSR-4 autoloading, maybe we should automatically uppercase the folder name. In the above case, the folder created inside my `src` folder was `post` and it should be `Post`. The same could be made with class name - make it automatically CamelCased.

**Comment by iruzevic** [comment]
fixed
