### ISSUE TITLE
Localization missing in blocks

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#92]
Currently, there is no way to provide localization, in the same way, it's possible in admin scripts and theme scripts

https://github.com/infinum/eightshift-libs/blob/f4c5552dc46316ee54e7a4e3b506362ec101e777/src/Enqueue/Blocks/AbstractEnqueueBlocks.php#L40-L52

This should be added as well.

**Comment by dingo-d** [comment]
There is a workaround tho. In theme's `EnqueueBlocks` class one needs to just override the `enqueueBlockEditorScript()` method like
```php
	/**
	 * Enqueue blocks script for editor only.
	 *
	 * @return void
	 */
	public function enqueueBlockEditorScript(): void
	{
		parent::enqueueBlockEditorScript();

		$handle = "{$this->getAssetsPrefix()}-block-editor-scripts";

		foreach ($this->getLocalizations() as $objectName => $dataArray) {
			\wp_localize_script($handle, $objectName, $dataArray);
		}
	}
```

**Comment by iruzevic** [comment]
Fixed
