### ISSUE TITLE
[BUG] getManifest missing throwable error

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-libs#98]
https://github.com/infinum/eightshift-libs/blob/57498081cb1fa8c3021d2aa943ac51d2b6801ade/src/Helpers/Components.php#L125-L135

the `getManifest` helper is missing the `throw` keyword, and on top of that, everywhere it's used a `try/catch` block should be added so that that exception can be caught.

**Comment by dingo-d** [comment]
I don't think all the exceptions were fixed (lines 48 and 96): https://github.com/infinum/eightshift-libs/blob/3.0.0/src/Helpers/Components.php

**Comment by iruzevic** [comment]
This is done
